# Generated by Django 2.2 on 2022-05-04 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='name',
            field=models.CharField(default='NO GAME', max_length=200),
        ),
    ]
